### ISSUE TITLE
Сканнер работает не правильно.

### ISSUE THREAD

**Issue by ShadowZ1xy** [ACA-Java-team/Black-Jack-game#1]
В директории **core** в классе **Choices** есть функция **move()** (25 строка) который запрашивает у пользователя ввод одного из 4 пунктов, если пользователь вводит не существующий пункт работает:  `System.out.println("Error - type again.");`

Проблема/баг в том что программа не ждет сканнера и сразу переходит на выполнение ветки **default** в **switch**.

```
int move() {
        System.out.println("Type your move- ");
        System.out.println("1   or   \"add\"     : for add additional card.");
        System.out.println("2   or   \"double\"  : for double your bet.");
        System.out.println("3   or   \"check\"   : for check cards (end round).");
        System.out.println("4   or   \"fold\"    : for instant lose but back 1/2 to your bet.");
        while (true) {
            System.out.println();
            System.out.print("Type: ");
            String choice = scanner.nextLine();
            switch (choice) {
                case "1":
                case "add":
                    return 1;
                case "2":
                case "double":
                    return 2;
                case "3":
                case "check":
                    return 3;
                case "4":
                case "fold":
                    return 4;
                default:
                    System.out.println("Error - type again.");
                    break;
            }
        }
}
```

**Comment by Mariam1911** [comment]
@ShadowZ1xy es knayem kporcem haskanam incha anum u xi chi chisht ashxatum, uxxaki es et xaxi kanonnery chgitem, ete inchvor texic nayel es nor es cragiry uxarkel linky uxarki vor esel et nuyny nayem, ete che uxaki es kgtnem internetic

**Comment by ShadowZ1xy** [comment]
> @ShadowZ1xy es knayem kporcem haskanam incha anum u xi chi chisht ashxatum, uxxaki es et xaxi kanonnery chgitem, ete inchvor texic nayel es nor es cragiry uxarkel linky uxarki vor esel et nuyny nayem, ete che uxaki es kgtnem internetic

Xaxi kanonner@ henc projecti opisaniayum ka, bayc problemi mej vochmi xaxi mechanicayi mas chka, @nenc vor hangist karoxes nayel u porcel lucel)

**Comment by Mariam1911** [comment]
@ShadowZ1xy lav kporcem

**Comment by ShadowZ1xy** [comment]
Исправил баг с помощью добавлении второго сканнера на ту же переменную, но причина бага осталась не известна.

```
String choice = scanner.nextLine();
choice = scanner.nextLine();
```

**Comment by ShadowZ1xy** [comment]
Из за сложности исправление бага я решил переписать часть кода чтобы избежать использование того что вызывает его.
К сожалению исправить сам баг не получился.
